# Global Settings
# The settings for the CLI.

[tool.pydantic_settings_export]
# default_settings: array
# The default settings to use. The settings are applied in the order they are
# listed.
# Default: []
# Examples: ["settings:settings"], ["app.config.settings:Settings","app.config.settings.dev:Settings"]
# default_settings = []

# root_dir: Path
# The project directory. Used for relative paths in the configuration file and
# .env file. If not set, will be the same as project_dir.
# Default: "<project_dir>"
# root_dir = "<project_dir>"

# project_dir: Path
# The project directory. Used for importing settings.
# Default: "<project_dir>"
# project_dir = "<project_dir>"

# respect_exclude: boolean
# Respect the exclude attribute in the fields.
# Default: true
# respect_exclude = true

# env_file: Path | NoneType
# The path to the .env file to load environment variables. Useful when you have a
# Settings class/instance, which requires values while running.
# Default: null
# env_file =

# Relative Directory Settings
# Settings for the relative directory.

[tool.pydantic_settings_export.relative_to]
# replace_abs_paths: boolean
# Replace absolute paths with relative path to project root.
# Default: true
# replace_abs_paths = true

# alias: string
# The alias for the relative directory.
# Default: "<project_dir>"
# alias = "<project_dir>"
